let w = {
  location: "Singapore",
  current: {
    day: "Today",
    date: "2019-06-13",
    low: 82,
    high: 84,
    text: "Thunderstorms",
    code: 4,
    temp_f: 82,
    temp_c: "28",
    high_c: "29",
    high_f: 84,
    low_c: "28",
    low_f: 82,
    icon: "local:weather_condition_icon_3",
  },
  forecast: [
    {
      day: "Fri",
      date: "2019-06-14",
      text: "Thunderstorms",
      code: 4,
      high_f: 84,
      high_c: "29",
      low_f: 82,
      low_c: "28",
      icon: "local:weather_condition_icon_3",
    },
    {
      day: "Sat",
      date: "2019-06-15",
      text: "Thunderstorms",
      code: 4,
      high_f: 83,
      high_c: "28",
      low_f: 81,
      low_c: "27",
      icon: "local:weather_condition_icon_3",
    },
    {
      day: "Sun",
      date: "2019-06-16",
      text: "Thunderstorms",
      code: 4,
      high_f: 83,
      high_c: "28",
      low_f: 82,
      low_c: "28",
      icon: "local:weather_condition_icon_3",
    },
    {
      day: "Mon",
      date: "2019-06-17",
      text: "Thunderstorms",
      code: 4,
      high_f: 84,
      high_c: "29",
      low_f: 82,
      low_c: "28",
      icon: "local:weather_condition_icon_3",
    },
    {
      day: "Tue",
      date: "2019-06-18",
      text: "Thunderstorms",
      code: 4,
      high_f: 85,
      high_c: "29",
      low_f: 82,
      low_c: "28",
      icon: "local:weather_condition_icon_3",
    },
    {
      day: "Wed",
      date: "2019-06-19",
      text: "Thunderstorms",
      code: 4,
      high_f: 83,
      high_c: "28",
      low_f: 81,
      low_c: "27",
      icon: "local:weather_condition_icon_3",
    },
  ],
  attribution_link: "webview:https://www.yahoo.com/?ilc=401",
  background_image: "local:weather_condition_bg_3",
  default_temperature_unit: "c",
  greeting: "Good Morning!",
  barcode: "355655090012297",
  zone: "4",
};

export default w;
